-- MySQL Script generated by MySQL Workbench
-- vie 28 feb 2020 07:55:33 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cities` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stations` (
  `id` INT NOT NULL,
  `adress` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stations_Cities1_idx` (`city_id` ASC),
  CONSTRAINT `fk_Stations_Cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`Cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trains` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paths`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paths` (
  `id` INT NOT NULL,
  `destiny` INT NOT NULL,
  `origin` INT NOT NULL,
  `train_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Path_Stations1_idx` (`destiny` ASC),
  INDEX `fk_Path_Stations2_idx` (`origin` ASC),
  INDEX `fk_Path_Train1_idx` (`train_id` ASC),
  CONSTRAINT `fk_Path_Stations1`
    FOREIGN KEY (`destiny`)
    REFERENCES `mydb`.`Stations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Path_Stations2`
    FOREIGN KEY (`origin`)
    REFERENCES `mydb`.`Stations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Path_Train1`
    FOREIGN KEY (`train_id`)
    REFERENCES `mydb`.`Trains` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
