-- MySQL Script generated by MySQL Workbench
-- lun 09 mar 2020 07:01:15 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CITIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CITIES` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STATIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STATIONS` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `ADDRESS` VARCHAR(45) NULL,
  `CITY_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_STATIONS_CITIES_idx` (`CITY_ID` ASC),
  CONSTRAINT `fk_STATIONS_CITIES`
    FOREIGN KEY (`CITY_ID`)
    REFERENCES `mydb`.`CITIES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PATHS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PATHS` (
  `ID` INT NOT NULL,
  `DESTINY_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PATHS_STATIONS1_idx` (`DESTINY_ID` ASC),
  CONSTRAINT `fk_PATHS_STATIONS1`
    FOREIGN KEY (`DESTINY_ID`)
    REFERENCES `mydb`.`STATIONS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRANSPORT_ENTITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TRANSPORT_ENTITY` (
  `ID` INT NOT NULL,
  `MODEL` VARCHAR(45) NULL,
  `WEIGHT` INT NULL,
  `PATH_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TRANSPORT_ENTITY_PATHS1_idx` (`PATH_ID` ASC),
  CONSTRAINT `fk_TRANSPORT_ENTITY_PATHS1`
    FOREIGN KEY (`PATH_ID`)
    REFERENCES `mydb`.`PATHS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAXIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TAXIS` (
  `ID` INT NOT NULL,
  `COMPANY` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ID`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`TRANSPORT_ENTITY` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BUSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BUSES` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ID`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`TRANSPORT_ENTITY` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRAINS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TRAINS` (
  `ID` INT NOT NULL,
  `WAGONS` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `ID`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`TRANSPORT_ENTITY` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
