-- MySQL Script generated by MySQL Workbench
-- vie 28 feb 2020 04:43:29 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema n2YPKzLy0Y
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema n2YPKzLy0Y
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `n2YPKzLy0Y` DEFAULT CHARACTER SET utf8 ;
USE `n2YPKzLy0Y` ;

-- -----------------------------------------------------
-- Table `n2YPKzLy0Y`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n2YPKzLy0Y`.`Cities` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `n2YPKzLy0Y`.`Stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n2YPKzLy0Y`.`Stations` (
  `id` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stations_Cities_idx` (`Cities_id` ASC),
  CONSTRAINT `fk_Stations_Cities`
    FOREIGN KEY (`Cities_id`)
    REFERENCES `n2YPKzLy0Y`.`Cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `n2YPKzLy0Y`.`Trains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n2YPKzLy0Y`.`Trains` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `n2YPKzLy0Y`.`Paths`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `n2YPKzLy0Y`.`Paths` (
  `id` INT NOT NULL,
  `destiny` INT NOT NULL,
  `origin` INT NOT NULL,
  `train_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Paths_Stations1_idx` (`destiny` ASC),
  INDEX `fk_Paths_Stations2_idx` (`origin` ASC),
  INDEX `fk_Paths_Trains_idx` (`train_id` ASC),
  CONSTRAINT `fk_Paths_Stations1`
    FOREIGN KEY (`destiny`)
    REFERENCES `n2YPKzLy0Y`.`Stations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paths_Stations2`
    FOREIGN KEY (`origin`)
    REFERENCES `n2YPKzLy0Y`.`Stations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paths_Train1`
    FOREIGN KEY (`train_id`)
    REFERENCES `n2YPKzLy0Y`.`Trains` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;